/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_NativeAddExpression */

#ifndef _Included_lib_NativeAddExpression
#define _Included_lib_NativeAddExpression
#ifdef __cplusplus
extern "C" {
#endif
#undef lib_NativeAddExpression_serialVersionUID
#define lib_NativeAddExpression_serialVersionUID 1010267344516507320i64
/*
 * Class:     lib_NativeAddExpression
 * Method:    eval
 * Signature: (Llib/Map;)Llib/Constant;
 */
JNIEXPORT jobject JNICALL Java_lib_NativeAddExpression_eval
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
